export const metadata = {
    title: "Login Page",
    description: "Generated by create next app",
  };

export default function Login(){
    return (
        <div>
        <h1>Login Page</h1>
        </div>
    );
}