export const metadata = {
    title: "Blogs",
    description: "Generated by create next app",
  };
export default async function Blog(){
    await new Promise(resolve=>{
        setTimeout(()=>{
            resolve('intentional delay');
        }, 2000);
    })
    return(
        <div>
        <h1>This is Blog Page</h1>
    </div>
    );
}