export const metadata = {
    title: "Profile",
    description: "Generated by create next app",
  };
export default function Profile(){
    return(
        <div>
        <h1>Profile of mine</h1>
    </div>
    );
}