import { Metadata } from "next";

import GlobalNavigation from "./global-navigation";


export const metadata:Metadata = {
  title: {
    default: 'Next Basic',
    template: "%s | Next Basic",
  },
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor:'lightblue',
            padding: '1rem'
          }}
        >
          Header
        </header>
        <GlobalNavigation/>
        {children}
        <footer
          style={{
            backgroundColor: 'aliceblue',
            padding: '1rem'
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}