import { Metadata } from "next";

import Link from "next/link";

export const metadata:Metadata = {
  title: {
    default: 'Next Basic',
    template: "%s | Next Basic",
  },
  description: "Generated by create next app",
};

const navLinks = [
  {name: "Home", href:'/'},
  {name: "Register", href:'/register'},
  {name: "Login", href:'/login'},
]

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor:'lightblue',
            padding: '1rem'
          }}
        >
          Header
        </header>
        {navLinks.map((link)=>{
          return (
            <Link href={link.href} key={link.name}>{link.name}</Link>
          )
        })}
        {children}
        <footer
          style={{
            backgroundColor: 'aliceblue',
            padding: '1rem'
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}