export const metadata = {
    title: "Not Found",
    description: "Generated by create next app",
  };
export default function NotFound(){
    return (
        <div>
        <h1>Not Found</h1>
        <h5>Requested Page is Not found!</h5>
        </div>
    );
}