export const metadata = {
    title: "Products",
    description: "Generated by create next app",
  };
export default function ProductList(){
    return <div>
        <h1>Product List</h1>
        <ul>
            <li>Product1</li>
            <li>Product2</li>
            <li>Product3</li>
        </ul>
    </div>;
}