import Link from "next/link";

export const metadata = {
    title: "Products",
    description: "Generated by create next app",
};
export default function ProductList() {

    return <div>
        <Link href={'/'}>Blog</Link>

        <h1>Product List</h1>
        <ul>
            <li>
                <Link href={'/products/1'}>Product1</Link>
            </li>
            <li>
                <Link href={'/products/2'}>Product2</Link>
            </li>
            <li>
                <Link href={'/products/3'}>Product3</Link>
            </li>
        </ul>
    </div>;
}