"use client";

import { Metadata } from "next";

import { useState } from "react";

export const metadata:Metadata = {
  title: {
    default: 'Next Basic',
    template: "%s | Next Basic",
  },
  description: "Generated by create next app",
};



export default function AuthLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  const [input, setInput] = useState('');
  return (
        <div>
          <input type="text" value={input} onChange={(e)=> setInput(e.target.value)}/>
          {children}
        </div>
  );
}